name: firebasewithnotification
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  geolocator: ^13.0.2
  flutter_localization: ^0.3.1
  firebase_auth: ^5.5.1
  animations: ^2.0.11
  lottie: ^3.1.2
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1
  provider: ^6.1.4

dev_dependencies:
  flutter_native_splash: ^2.4.4

flutter_test:
  sdk: flutter

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/Pattern.png
    - images/Order food.png
    - images/Take Away.png
    - images/maps.png
    - assets/lang/
    - images/Sent Message.png
    - images/animation.png
    - images/balloon1.png
    - images/balloon2.png
    - images/plant.png
    - assets/success_animation.json
    - images/cheese-burger-details.png
    - images/Chicken Burger.png
    - images/Onion Pizza.png
    - images/Spicy Shawarma.png
    - images/Empty State.png
    - images/Order ID.png
    - images/photo.png

    - images/Pattern (1).png
